(define (double x)
  (+ x x))
(define (halve x)
  (if (even? x)
      (/ x 2)
      'not-even))
(define (* a b)
  (cond ((or (= b 0) (= a 0)) 0)
        ((even? b) (* (double a) (halve b)))
        (else (+ a (* a (- b 1))))))
(* 0 101)
(* 11 111)