(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define (make-segment start end)
  (cons start end))
(define (start-segment segment)
  (car segment))
(define (end-segment segment)
  (cdr segment))
(define (make-point x y) (cons x y))
(define (x-point point) (car point))
(define (y-point point) (cdr point))

(define (midpoint-segment segment)
  (average-point (start-segment segment)
                 (end-segment segment)))
(define (average-point p1 p2)
  (make-point (average (x-point p1) (x-point p2))
              (average (y-point p1) (y-point p2))))
(define (average a b) (/ (+ a b) 2))

(let ((start (make-point 19 92))
      (end (make-point 9 22)))
  (print-point (midpoint-segment (make-segment start end))))

(print-point (midpoint-segment (make-segment (make-point 7 23) (make-point 9 38))))