(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define (make-segment start end)
  (cons start end))
(define (start-segment segment)
  (car segment))
(define (end-segment segment)
  (cdr segment))
(define (make-point x y) (cons x y))
(define (x-point point) (car point))
(define (y-point point) (cdr point))

(define (midpoint-segment segment)
  (average-point (start-segment segment)
                 (end-segment segment)))
(define (average-point p1 p2)
  (make-point (average (x-point p1) (x-point p2))
              (average (y-point p1) (y-point p2))))
(define (average a b) (/ (+ a b) 2))

(define (make-rectangle-point p1 p2 p3)
  (cons 1 (cons p1 (cons p2 p3))))
(define (make-rectangle-segment s1 s2)
  (cons 2 (cons s1 s2)))
(define (lenth-segment segment)
  (define (square x) (* x x))
  (let ((p1 (car segment))
        (p2 (cdr segment)))
    (sqrt (+ (square (- (x-point p1) (x-point p2)))
             (square (- (y-point p1) (y-point p2)))))))
(define (chang-rectangle rectangle)
  (if (= (car rectangle) 1)
      (lenth-segment (make-segment (cadr rectangle) (caddr rectangle)))
      (lenth-segment (cadr rectangle))))
(define (kuan-rectangle rectangle)
  (if (= (car rectangle) 1)
      (lenth-segment (make-segment (caddr rectangle) (cdddr rectangle)))
      (lenth-segment (cddr rectangle))))

(define (perimeter rectangle)
  (* 2 (+ (chang-rectangle rectangle) (kuan-rectangle rectangle))))
(define (area rectangle)
  (* (chang-rectangle rectangle) (kuan-rectangle rectangle)))

(let ((rectangle1 (make-rectangle-point (make-point 1 1)
                                        (make-point 3 1)
                                        (make-point 3 2)))
      (rectangle2 (make-rectangle-segment (make-segment (make-point 1 1)
                                                        (make-point 3 1))
                                          (make-segment (make-point 1 1)
                                                        (make-point 1 2)))))
  (display "perimeter:")
  (perimeter rectangle1)
  (newline)
  (perimeter rectangle2)
  (newline)
  (display "area:")
  (newline)
  (area rectangle1)
  (newline)
  (area rectangle2))